In [41]:
import numpy as np
import time
import math

# WAYS TO MAKE ARRAYS

In [ ]:
int_array = np.array([1,4,2,5,6])

print(int_array)

[1.  4.  2.  5.5 6. ]


creating an array is straightforward

In [ ]:
mixed_array = np.array([3.14,20,52.2,10])

print(mixed_array)

[ 3.14 20.   52.2  10.  ]


If a numpy array contains both integers and doubles, all integers are made into doubles by default. You can explicitly set the data type of the resulting array however, which I'll cover here.

In [ ]:
explicit_set_array = np.array([1,4,2,5,6], dtype=np.float64)

print(explicit_set_array)

If you want to explicitly set the type of an array, you can use the `dtype` keyword.

In [12]:
arr_multidim = np.array([range(i, i + 3) for i in [2, 4, 6]])

print(arr_multidim)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


Unlike python lists, NumPy arrays can be multidimensional. Above is a two-dimensional array, where each inner list is its own row.

In [16]:
zero_arr = np.zeros((3,2),dtype=int)

print(zero_arr)

[[0 0]
 [0 0]
 [0 0]]


You can create an array filled with zeroes by using np.zeros(quantity).

In [15]:
ones_arr = np.ones((3,5),dtype=int)

print(ones_arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


You can create an array filled with ones by using np.ones(quantity). Behaves exactly like np.zeros otherwise.

In [17]:
osix_arr = np.full((7,12),2006)

print(osix_arr)

[[2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]
 [2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]
 [2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]
 [2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]
 [2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]
 [2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]
 [2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006]]


You can create an array filled with a specific number by using np.full(quantity, num). Behaves exactly like np.zeros otherwise.

In [18]:
arange_arr = np.arange(0,20,2)

print(arange_arr)

[ 0  2  4  6  8 10 12 14 16 18]


You can create an array filled with a linear sequence using np.arange. This one starts at 0 (arg 1), ends at 20 (arg 2), in steps of 2 (arg 3).

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

You can create an array of #arg3 evenly spaced values between arg 1 and arg 2 using np.linspace.

In [ ]:
rand_arr = np.random.random((3,3))

print(rand_arr)

You can create an array of random values using np.random.random().

In [23]:
arr_randNorm = np.random.normal(0,1,(3,3))

print(arr_randNorm)

[[-1.57779513  1.04683929 -0.74728627]
 [ 1.07748531 -0.13368239  1.41261899]
 [-0.57858051 -1.70672822  1.32541251]]


In [24]:
arr_randInt = np.random.randint(0,10,(3,3))

print(arr_randInt)

[[5 6 9]
 [6 3 8]
 [8 7 6]]


# ARRAYS AND THEIR PROPERTIES

In [ ]:
np.random.seed(0) # seed for reproducibility

In [30]:
arr_1d = np.random.randint(10,size=6)

arr_2d = np.random.randint(10,size=(3,4))

arr_3d = np.random.randint(10, size=(3,4,5))

Each array has attributes, including:

`ndim` - The number of dimensions

`shape` - The size of each dimension

`size` - The total size of the array

`dtype` - The data type of the array

`itemsize` - The size of each array element in bytes

`nbytes` - The total size of the array in bytes

> Generally, `nbytes` should be equal to `itemsize * size`.

In [27]:
print("arr_3d ndim: ", arr_3d.ndim)
print("arr_3d shape:", arr_3d.shape)
print("arr_3d size: ", arr_3d.size)
print("arr_3d dtype: ", arr_3d.dtype)
print("arr_3d itemsize: ", arr_3d.itemsize)
print("arr_3d nbytes: ", arr_3d.nbytes)

arr_3d ndim:  3
arr_3d shape: (3, 4, 5)
arr_3d size:  60
arr_3d dtype:  int64
arr_3d itemsize:  8
arr_3d nbytes:  480


Indexing in numpy is very similar to standard Python.

you know how to do this already.

In a multi-dimensional array, items can be accessed using a comma separated indice tuple (eg. arr_3d[3,2])

NumPy arrays have a fixed type however, so any doubles will be converted to integers and vice versa.

Likewise, slicing is also very similar.

Slicing multidimensionally can be done very similarly, with multiple slices being done via commas.


# HOWEVER!

Array slices return views, rather than copies of the array data. To *copy*, just put .copy() at the end.

In [28]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

np.concatenate allows you to join two or more arrays in NumPy, and it can also be used for 2D arrays.

In [35]:
grid = np.concatenate([arr_2d,arr_2d])

print(grid)

[[0 4 0 1]
 [7 6 7 4]
 [1 8 7 2]
 [0 4 0 1]
 [7 6 7 4]
 [1 8 7 2]]


You can also designate which axis the function wil concatenate along.

In [36]:
grid = np.concatenate([arr_2d,arr_2d], axis=1)

print(grid)

[[0 4 0 1 0 4 0 1]
 [7 6 7 4 7 6 7 4]
 [1 8 7 2 1 8 7 2]]


When working with arrays of mixed dimensions, it can be better to use np.vstack and np.hstack functions.

Splitting can be done using np.split, np.hsplit, and np.vsplit.

# VECTORIZATION DEMO

In [38]:
def loop_sum(arr):
    total = 0
    for idx in arr:
        total += idx

    return total

def vectorized_sum(arr):
    return np.sum(arr)

In [ ]:

arr = np.random.rand(100_000_000)

start = time.time()
loop_sum(arr)
loop_speed = time.time() - start
print(f"Loop: {loop_speed:.4f}s")


start = time.time()
vectorized_sum(arr)
vectorized_speed = time.time() - start
print(f"Vectorized: {vectorized_speed:.4f}s")

print(f"Speedup: {loop_speed/vectorized_speed:.1f}x")

Loop: 7.7485s
Vectorized: 0.0448s
Speedup: 173.1x


Vectorized is about 80-180x times faster than looping, especially with larger values.